# Generated by Django 4.1.3 on 2023-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='dessert', max_length=255),
        ),
    ]
